import ICO_BACK from '../../../assets/ico/ico_back.svg';
import ICO_CLOSE from '../../../assets/ico/ico_close.svg';
import ICO_FOLD from '../../../assets/ico/ico_fold.svg';
import ICO_MENU from '../../../assets/ico/ico_menu.svg';
import ICO_UNFOLD from '../../../assets/ico/ico_unfold.svg';
import ICO_SEARCH from '../../../assets/ico/ico_search.svg';
import ICO_ARROW from '../../../assets/ico/ico_arrow.svg';
import ICO_CONFIG from '../../../assets/ico/ico_config.svg';
import ICO_PROFILE from '../../../assets/ico/ico_profile.svg';
import ICO_FILTER from '../../../assets/ico/ico_filter.svg';
import ICO_NOTICE from '../../../assets/ico/ico_notice.svg';

exports.ICO_BACK = ICO_BACK;
exports.ICO_CLOSE = ICO_CLOSE;
exports.ICO_FOLD = ICO_FOLD;
exports.ICO_MENU = ICO_MENU;
exports.ICO_UNFOLD = ICO_UNFOLD;
exports.ICO_SEARCH = ICO_SEARCH;
exports.ICO_ARROW = ICO_ARROW;
exports.ICO_CONFIG = ICO_CONFIG;
exports.ICO_PROFILE = ICO_PROFILE;
exports.ICO_FILTER = ICO_FILTER;
exports.ICO_NOTICE = ICO_NOTICE;